export var data = { //since board is isometric the rows begin from the back
  obj: [
    [ //row1
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [{ zimon: "Tree" }] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },


      
    ],
    [//row2
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [{ zimon: "Tree" }] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row3
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row4
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [{ zimon: "Tree" }] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row5
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [{ zimon: "Tree" }] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row6
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row7
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row8
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#ffc0cb", icon: null, items: [] }, //landmark for library
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row9
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "g", color: "#ffc0cb", icon: null, items: [] },//landmark for park
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row10
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row11
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row12
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [{ zimon: "Tree" }] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row13
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [{ zimon: "Tree" }] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row14
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row15
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row16
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row17
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "x", color: "#ffc0cb", icon: null, items: [] }, //landmark for school
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row18
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [{ zimon: "Tree" }] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row19
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "g", color: "#acd241", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],
    [//row20
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "0", color: "#333333", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "o", color: "#40E0D0", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "r", color: "#fb4758", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
      { data: "x", color: "#555555", icon: null, items: [] },
    ],

    
  ],
  zimon: 1,
  info: "https://zimjs.com/zimon/",
};
